name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install vsce
      run: yarn i -g vsce

    - name: Install Dependencies
      run: yarn install

    - name: Publish Extension
      run: vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
